### ISSUE TITLE
Attendance at strategy development meeting: Ethics strategy (Q2)

### ISSUE THREAD

**Issue by VanCardui** [SingularityNet-Ambassador-Program/AI-Ethics-Workgroup#12]
Meeting took place on Ist July 2024

Attendees: **$30 each** to: 

- Jenn
- Duke
- Ese
- Kenichi
- Gorga

Note that people will be paid the same whether they attended the meeting live, or watched the recording afterwards

Notes from all 3 strategy scoping meetings are here https://docs.google.com/document/d/1eHe5PmGPpjlX7VpCxQECOHwXDEl5RRnQ1jVyUhus1tg/edit?usp=sharing

**Comment by JennMayshiogie** [comment]
Ethics Strategy Draft Writer Group is created by @EseWilliams and the members are @EseWilliams, @dukepeter and @JennMayshiogie

**Comment by colleenpridemore** [comment]
Is this connected to the right issue #, Jenni?
