### ISSUE TITLE
Research strategy (writing)  Q2

### ISSUE THREAD

**Issue by VanCardui** [SingularityNet-Ambassador-Program/AI-Ethics-Workgroup#14]
**$100 each** to
- Effiom
- Vasu
- Clement

on delivery of a draft on or before 19th July 2024

Initial notes for all 3 strategies are here https://docs.google.com/document/d/1eHe5PmGPpjlX7VpCxQECOHwXDEl5RRnQ1jVyUhus1tg/edit?usp=sharing

**Comment by ClementUmoh** [comment]
**Final Research Strategy Draft Document**

https://docs.google.com/document/d/1jLm9wgGY0-MjzAza9u7eXI5BP13XKTMy6fwoCdsgk2U/edit?usp=drive_link

**Comment by ClementUmoh** [comment]
Ok our group has decided to ration the rewards in the following way:

Effiom - **$125**
Clement - **$125**
Osmium - **$50**
