### ISSUE TITLE
Research strategy (editing) Q2

### ISSUE THREAD

**Issue by VanCardui** [SingularityNet-Ambassador-Program/AI-Ethics-Workgroup#15]
**$100 each** to
- Peegee
- Colleen

on delivery of an edited draft, on or before 2nd August 2024

**Comment by VanCardui** [comment]
Just for reference, you'll find the draft strategy from your writing team in the relevant issue https://github.com/SingularityNet-Ambassador-Program/AI-Ethics-Workgroup/issues/14

Here's a direct link to it https://docs.google.com/document/d/1jLm9wgGY0-MjzAza9u7eXI5BP13XKTMy6fwoCdsgk2U/edit?usp=drive_link

**Comment by colleenpridemore** [comment]
Here you go...
[FINAL DRAFT edit- RESEARCH STRATEGY FOR SINGULARITYNET AI ETHICS WG.docx.docx](https://github.com/user-attachments/files/16476894/FINAL.DRAFT.edit-.RESEARCH.STRATEGY.FOR.SINGULARITYNET.AI.ETHICS.WG.docx.docx)
[Appendix - Research Strategy.docx](https://github.com/user-attachments/files/16476915/Appendix.-.Research.Strategy.docx)

**Comment by colleenpridemore** [comment]
Here are our submissions, they include a _**Final Draft of Research Strategy - edited**_.
and a _**Research Strategy Appendix**_.

[https://docs.google.com/document/d/1ZrVeMg5Nw6kcHs2tu3oBPSQHFxQeL_a6HUInL5SJ2eY/edit](https://docs.google.com/document/d/1ZrVeMg5Nw6kcHs2tu3oBPSQHFxQeL_a6HUInL5SJ2eY/edit)
[https://docs.google.com/document/d/1V3-kwD4ECeFpE5IBEznuNlhYEkoq6L8l2_E33xUn6Uk/edit?pli=1#heading=h.m28nqb706wia](https://docs.google.com/document/d/1V3-kwD4ECeFpE5IBEznuNlhYEkoq6L8l2_E33xUn6Uk/edit?pli=1#heading=h.m28nqb706wia)

**Comment by SucrenSpice** [comment]
If you didn't receive payments for this today, please know that payments will be made next Tuesday. The reason is because an error was made when sending the tasks for payment on Dework. The sign $ was used instead of USD to place the fund request. Apologies for this.  @colleenpridemore @Peegee24

**Comment by colleenpridemore** [comment]
No worries, thank you for letting me know.
