### ISSUE TITLE
Knowledge management strategy (writing) Q2

### ISSUE THREAD

**Issue by VanCardui** [SingularityNet-Ambassador-Program/AI-Ethics-Workgroup#16]
**$100 each** to
- Stephen
- Ayo
- Onize

on delivery of a draft, on or before 19th July 2024

Initial notes for all 3 strategies are here https://docs.google.com/document/d/1eHe5PmGPpjlX7VpCxQECOHwXDEl5RRnQ1jVyUhus1tg/edit?usp=sharing

**Comment by stephen-rowan** [comment]
## Draft Knowledge Management Strategy 

https://docs.google.com/document/d/1yo9MuYSA_4ZOkMH2KJibUu6C7tlzHFe9e4YC7mvVl6g/edit?usp=sharing (view link)

**Comment by stephen-rowan** [comment]
Split contribution budget as follows -

Ayo - $ 50
Onize - $ 50
Stephen - $ 200

**Comment by Rejayolie** [comment]
This is Onize

I found out that there was a pending sharing formula discussion for our draft group between Ayo, Stephen and I. I am okay with the $200 to Stephen and $50 each to Ayo and I, Ayo and I Ideated, while Stephen wrote the draft.

The formula is fair to me, Stephen suggested , Ayo agreed and now I following up that I agree too.

**Comment by VanCardui** [comment]
After discussion, Onize says she didn't contribute as much as she would have liked, so maybe $50 is too much
To be discussed with Stephen and Ayo before making any decision on it.
Onize: If everyone feels it's to much then OK
