### ISSUE TITLE
Ethics strategy (writing)  Q2

### ISSUE THREAD

**Issue by VanCardui** [SingularityNet-Ambassador-Program/AI-Ethics-Workgroup#17]
**$100 each** to
- Jenn
- Duke
- Ese

on delivery of a draft, on or before 19th July 2024

Initial notes for all 3 strategies are here https://docs.google.com/document/d/1eHe5PmGPpjlX7VpCxQECOHwXDEl5RRnQ1jVyUhus1tg/edit?usp=sharing

**Comment by JennMayshiogie** [comment]
Our 1st meeting for the Ethics Strategy (Writing)-ESW is already held in July  8th, 2024 at 19:00-20:00 UTC

Decide that @JennMayshiogie will start working a draft from July 10th, 2024 and will share the draft Google Doc link for @dukepeter and @EseWilliams on the same date or at the early July 11th, 2024 on our Discord ESW group. Draft will be share publicly on our AI Ethics WG on July 18th, 2024 to get feedback. Kindly let me know if there are any suggestions regarding the timeframe.

Thanks to
@EseWilliams @dukepeter @VanCardui & @Andre-Diamond

**Comment by JennMayshiogie** [comment]
Tentative Draft link shared by @JennMayshiogie for Ethics Strategy writing:

https://docs.google.com/document/d/1O9gIX664jIXPcZ55fCqzkI3qXGgq6BXF22pwthhPuqI/edit?usp=sharing

feel free to check it out and add some ideas

**Comment by JennMayshiogie** [comment]
Draft of Tentative Ethics Strategy can be open in the same Google Doc link:

https://docs.google.com/document/d/1O9gIX664jIXPcZ55fCqzkI3qXGgq6BXF22pwthhPuqI/edit?usp=sharing

**Comment by JennMayshiogie** [comment]
I have proposed for Ethics Strategy Writer team to split the $300 incentive/reward:
- $130 to @JennMayshiogie for initiating the draft
- $120 to @EseWilliams for contributing to the draft within the timeframe
- $ 50 to @dukepeter for the late response to asynchronous work on the draft

**Comment by VanCardui** [comment]
After further thought, 2 members of the group said that they felt that an equal distribution ($100 per person) was fairer after all; and the 3rd member of the group said they were prepared to go along with this, although they do not agree.

**So the payment will be** 
$100 to Jenn
$100 to Duke
$100 to Ese.
