### ISSUE TITLE
Knowledge management strategy (editing)   Q2

### ISSUE THREAD

**Issue by VanCardui** [SingularityNet-Ambassador-Program/AI-Ethics-Workgroup#18]
**$100 each** to
- Sucre
- Tevo

on delivery of an edited draft, on or before 2nd August 2024

**Comment by VanCardui** [comment]
Just for reference, you'll find the draft strategy from your writing team in the relevant issue https://github.com/SingularityNet-Ambassador-Program/AI-Ethics-Workgroup/issues/16

Here's a direct link to it https://docs.google.com/document/d/1yo9MuYSA_4ZOkMH2KJibUu6C7tlzHFe9e4YC7mvVl6g/edit?usp=sharing

**Comment by SucrenSpice** [comment]
Here's the edited version: https://docs.google.com/document/d/1yo9MuYSA_4ZOkMH2KJibUu6C7tlzHFe9e4YC7mvVl6g/edit?pli=1&disco=AAABSxTuDfU

**Comment by SucrenSpice** [comment]
If you didn't receive payments for this today, please know that payments will be made next Tuesday. The reason is because an error was made when sending the tasks for payment on Dework. The sign $ was used instead of USD to place the fund request. Apologies for this.  @whitevo
