### ISSUE TITLE
Report-backs to GEI, Q3

### ISSUE THREAD

**Issue by VanCardui** [SingularityNet-Ambassador-Program/AI-Ethics-Workgroup#20]
Provide a brief reportback on the activities of the WG at each GEI Open Office meeting in Q3 2024.
Assigned to Jenn 
$20 per instance - total of 6 instances.
To be paid at the end of the quarter.
(NB the GEI meeting on 2nd July was just an introduction - no reportback was given)

- [x] 16th July
- [x] 30th July
- [x] 13th August (no meeting took place. WG agreed this should still be paid)
- [x] 27th August (no meeting  took place. WG agreed this should still be paid)
- [ ] 10th September
- [ ] 24th September (no reportback was done, and Jenn wasn't able to make the meeting)

**Comment by VanCardui** [comment]
16th July reportback doc https://docs.google.com/document/d/1IEYSnw4P4MUSn5vOT03VzauCl1tGlE7xgkEF-_Ra9Ac/

**Comment by JennMayshiogie** [comment]
30th July reportback doc https://docs.google.com/document/d/10aSXKo14xxbeZx5l0eH-Zqh-Eo8MKiIE4FU1Q7E_YjI/

**Comment by VanCardui** [comment]
Moving to Done

We agreed in meeting on 30th Sept that altho the reports may not have been presented in a GEI meeting, they were done, so should be paid as originally agreed
