### ISSUE TITLE
Documentation, 8th July meeting (Q3)

### ISSUE THREAD

**Issue by VanCardui** [SingularityNet-Ambassador-Program/AI-Ethics-Workgroup#23]
Write minutes for meeting on Mon 8th July and add to meeting summary tool

**Comment by colleenpridemore** [comment]
Where is the Meeting Summary Tool? I don't see it in the Git book, but then I could be blind. I'm trying to work off of my phone

**Comment by VanCardui** [comment]
hi Colleen - it's here https://archive-oracle.netlify.app/

**Comment by colleenpridemore** [comment]
yes thank you!  I also had the link you sent to me via DM awhile back, I forgot I asked here too.  :0)

**Comment by VanCardui** [comment]
Summary archived https://snet-ambassadors.gitbook.io/singularitynet-archive/timeline/2024/july-2024/week-28#ai-ethics-wg
