### ISSUE TITLE
WG async work support, Q3 2024

### ISSUE THREAD

**Issue by VanCardui** [SingularityNet-Ambassador-Program/AI-Ethics-Workgroup#25]
Co-ordinate and organise WG members who are working async or in small groups
Offer ongoing support via Discord WG channel and DMs

Assigned to LadyTempestt

**Comment by VanCardui** [comment]
Update in meeting on 22nd July

It's quite hard to be in the middle and stay neutral!

**Comment by Lady-Tempest** [comment]
Update on 5th August meeting

So far, I have had to prompt AI Ethics Strategy Writers and Editors to submit their expected drafts on or before the deadline; I went to the DMs of some people who were lost on what was expected of them and where they could get started, also frequently prompted people, some who were radio silent on their progress and whatnot.

It was interesting, a bit tricky, but everything I can handle though.

**Comment by Lady-Tempest** [comment]
Update on 2nd September 

Async work support is going smoothly so far with DM prompts/reminders/updates. Atm I'm not struggling to stay in the middle lol
