### ISSUE TITLE
NOT COMPLETED AND NOT PAYABLE: documenting GEI Open Office sessions

### ISSUE THREAD

**Issue by VanCardui** [SingularityNet-Ambassador-Program/AI-Ethics-Workgroup#34]
It would be useful to document the GEI Open Office sessions as well as our WG meetings. However, we did not think to include a budget line for this in our Q3 budget.

So, given that the WG has quite a lot of unspent budget for Q2, we propose to cost this under Q2 (see line 3a in https://docs.google.com/spreadsheets/d/1G9gvX5h3VQQTmOXRaM6y1dXOHVP2I1g_V2R4lOUtnDo/edit?usp=sharing)

This is to be ratified (or not) in the WG meeting on 22nd July 2024

**Comment by VanCardui** [comment]
ratified in meeting on 22nd July

**Comment by JennMayshiogie** [comment]
@JennMayshiogie will be documenting the total six (6) of GEI Open-Office Meeting in two (2) batch:
- Batch 1: Writes three (3) summary docs of GEI Open Office meeting on the date of Jul 16th, Aug 30th & Aug 13th. Will be published by Friday, Aug 23th, 2024.
- Batch 2: Writes three (3) summary docs of GEI Open Office meeting on the date of Aug 27th, Sep 10th & Sept 24th. Will be published by Wednesday, Sept 25th, 2024.

Kindly let me know if there are any subject to change.

**Comment by VanCardui** [comment]
Hi Jenn:
Just noting that due to the AGI-24 conference, there was no GEI meeting on Aug 13th.

Also note that re: adding the summaries to the Archives via the meeting summary tool, we use the AI Ethics WG template for this.

**Comment by VanCardui** [comment]
Vani will try once more to contact Jenn, and LeeLoo will check to see if read ai was theresuccessfully too; but if Jenn is not available, we might need to reassign this task

**Comment by VanCardui** [comment]
In meeting of 4th Nov we decided to leave this task as it is and not attempt to document the missing meetings

**Comment by VanCardui** [comment]
Whilst one of the meetings (Aug 13th) didn't happen due to AGI-24, none of the others were documented, and Jenn is uncontactable. 
So this Issue will be closed as unfinished; the cost will be changed to 0; and the $180 that was allocated for it will return to the WG pot.
