### ISSUE TITLE
Documentation  of WG meeting Mon 22nd July 2024

### ISSUE THREAD

**Issue by VanCardui** [SingularityNet-Ambassador-Program/AI-Ethics-Workgroup#37]
Document meeting and add to meeting summary tool

**Comment by colleenpridemore** [comment]
This task has been relinquished to Vani

**Comment by VanCardui** [comment]
very belatedly done! https://snet-ambassadors.gitbook.io/singularitynet-archive/timeline/2024/july-2024/week-30#ai-ethics-wg
