### ISSUE TITLE
Documentation of WG meeting 23rd Sept 2024

### ISSUE THREAD

**Issue by VanCardui** [SingularityNet-Ambassador-Program/AI-Ethics-Workgroup#57]
Note that this meeting was postponed from the week before, 16th Sept

**Comment by Lady-Tempest** [comment]
Link to the meeting summary here:

https://docs.google.com/document/d/1m8Mk-zAqysQA-oF0V_Kg3MSE9icGeZhT6_eVYH3Wrls/edit
