### ISSUE TITLE
Part 3: Event in Nigeria : VOLUNTEERS

### ISSUE THREAD

**Issue by VanCardui** [SingularityNet-Ambassador-Program/AI-Ethics-Workgroup#64]
This relates to https://github.com/SingularityNet-Ambassador-Program/AI-Ethics-Workgroup/issues/45
**Payment: Volunteers**
$100 each to the 4 volunteers, Clement, Ese, Ayo and Yemi; plus a share of Esther and LeeLoo's payments as speakers (which they waived, and which have been redistributed to the volunteers). So in total:

The total of $700 will all go to Duke, who will redistribute.

**Comment by SucrenSpice** [comment]
Payment has been sent to directly to the wallets of the volunteers
